-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jul 09, 2023 at 04:36 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `youtube_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `youtube_channels`
--

CREATE TABLE `youtube_channels` (
  `name` varchar(250) NOT NULL,
  `profile_Picture` varchar(400) NOT NULL,
  `description` varchar(800) NOT NULL,
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `youtube_channels`
--

INSERT INTO `youtube_channels` (`name`, `profile_Picture`, `description`, `id`) VALUES
('NBA', 'https://yt3.ggpht.com/urNLBJGryDamao5r0jmlTg84mIBOoaeJd6XR67j4nuRd0iRvv5g-MUgaowsWKCs8V_t4KwST=s88-c-k-c0x00ffffff-no-rj', 'The NBA is the premier professional basketball league in the United States and Canada. The league is truly global, with games and programming in 215 countries and territories in 47 languages. The NBA consists of 30 teams. The NBA offers real time access to live regular season NBA games with a subscription to NBA LEAGUE PASS, available globally for TV, broadband, and mobile.  Real-time Stats, Scores, Highlights and more are available to fans on web and mobile with the NBA App. \n\nFor news, stories, highlights and more, go to our official website at https://app.link.nba.com/e/NBA_site\n', 57);

-- --------------------------------------------------------

--
-- Table structure for table `youtube_channel_videos`
--

CREATE TABLE `youtube_channel_videos` (
  `title` varchar(250) NOT NULL,
  `videoLink` varchar(400) NOT NULL,
  `description` varchar(800) NOT NULL,
  `thumbnail` varchar(500) NOT NULL,
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `youtube_channel_videos`
--

INSERT INTO `youtube_channel_videos` (`title`, `videoLink`, `description`, `thumbnail`, `id`) VALUES
('16th Overall Pick Keyonte George Drops HUGE DOUBLE-DOUBLE | 33 PTS, 10 AST, 6 3PM', 'u7JIo8ABeTs', 'Led by Keyonte George\'s 33 points and 10 assists, the Utah Jazz defeat the LA Clippers, 105-99. Ochai Agbaji added 21 points, 9 rebounds and 5 assists for the Jazz, while Xavier Moon tallied 26 points and 4 rebounds for the Clippers. \n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/u7JIo8ABeTs/default.jpg', 1839),
('CLIPPERS vs JAZZ | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'vEcMufZWia8', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nLed by Keyonte George\'s 33 points and 10 assists, the Utah Jazz defeat the LA Clippers, 105-99. Ochai Agbaji added 21 points, 9 rebounds and 5 assists for the Jazz, while Xavier Moon tallied 26 points and 4 rebounds for the Clippers.', 'https://i.ytimg.com/vi/vEcMufZWia8/default.jpg', 1840),
('BUCKS vs SUNS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'VKX835xm1_E', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Milwaukee Bucks defeat the Phoenix Suns, 84-75. MarJon Beauchamp led the way with 20 points and 6 rebounds for the Bucks, while Tyler Cook added 14 points and 4 rebounds in the victory. Toumani Camara tallied 20 points and 8 rebounds for the Suns.', 'https://i.ytimg.com/vi/VKX835xm1_E/default.jpg', 1841),
('PACERS vs WIZARDS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'pYYbkzLW2MM', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Indiana Pacers defeat the Washington Wizards, 91-83. Bennedict Mathurin led the way with 27 points and 5 rebounds for the Pacers, while Isaiah Jackson added 21 points and 14 rebounds in the victory. Johnny Davis tallied 17 points, 4 rebounds and 3 assists for the Wizards, while Bilal Coulibaly added 9 points and 3 rebounds.', 'https://i.ytimg.com/vi/pYYbkzLW2MM/default.jpg', 1842),
('Tacko Fall Block ➡️ MarJon Beauchamp SELF ALLEY-OOP! 👀 | #Shorts', '02wfJ8Yk2Dw', '', 'https://i.ytimg.com/vi/02wfJ8Yk2Dw/default.jpg', 1843),
('#7 Overall Pick Bilal Coulibaly GOT UP for the Block! 🔥 | #Shorts', 'PYZG7jYQ4v8', '', 'https://i.ytimg.com/vi/PYZG7jYQ4v8/default.jpg', 1844),
('Doris Burke congratulates Kyle Kuzma on his new deal while interviewing Jordan Poole 😂 | #Shorts', 'sH3oxgpYEng', '', 'https://i.ytimg.com/vi/sH3oxgpYEng/default.jpg', 1845),
('BULLS vs GRIZZLIES | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'AHvhFjIT-GE', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Memphis Grizzlies defeated the Chicago Bulls, 87-80. Kenneth Lofton Jr. led the way with 23 points, 4 rebounds and 3 blocks for the Grizzlies, while Jake LaRavia added 15 points, 4 rebounds and 3 assists in the victory. Javon Freeman-Liberty tallied 24 points, 6 rebounds and 5 assists for the Bulls.', 'https://i.ytimg.com/vi/AHvhFjIT-GE/default.jpg', 1846),
('Richard Jefferson explains the inaugural NBA In-Season Tournament! 🍿 | #Shorts', 'S-N5OgDblJI', '', 'https://i.ytimg.com/vi/S-N5OgDblJI/default.jpg', 1847),
('The NBA Cup is Revealed for the First Time EVER! 🏆 | #Shorts', 'odjiCLVWDy0', '', 'https://i.ytimg.com/vi/odjiCLVWDy0/default.jpg', 1848),
('#6 Overall Pick Anthony Black Shines In His Summer League Debut!', '0XibbdITqWg', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Detroit Pistons defeat the Orlando Magic, 89-78.  Jalen Duren led the way with 17 points and 8 rebounds for the Pistons, while James Wiseman (16 points, 11 rebounds) and Ausar Thompson (7 points, 9 rebounds) added a combined 21 points in the victory.  Kevon Harris tallied 21 points and 6 rebounds for the Magic, while Anthony Black added 17 points, 5 rebounds and 5 assists', 'https://i.ytimg.com/vi/0XibbdITqWg/default.jpg', 1849),
('2023 In-Season Tournament East & West Groups Reveal!', '0MuEA5AreTI', 'Starting Nov. 3, all 30 teams will compete for the NBA Cup with 8 teams advancing into the knockout rounds! The tournament semis and championship game will be held in Las Vegas, Dec. 7 and 9! \n\nLearn more about the NBA\'s first-ever In-Season Tournament in the NBA App:  https://app.link.nba.com/-Tournament', 'https://i.ytimg.com/vi/0MuEA5AreTI/default.jpg', 1850),
('Wemby & Kareem Share a moment at NBA Con! 🔥| #Shorts', '85yb-mxD_14', '', 'https://i.ytimg.com/vi/85yb-mxD_14/default.jpg', 1851),
('2023 NBA In-Season Tournament Explained!', 'fT1Vk286308', 'Starting Nov. 3, all 30 teams will compete for the NBA Cup with 8 teams advancing into the knockout rounds! The tournament semis and championship game will be held in Las Vegas, Dec. 7 and 9! \n\nLearn more about the NBA\'s first-ever In-Season Tournament in the NBA App:  https://app.link.nba.com/-Tournament', 'https://i.ytimg.com/vi/fT1Vk286308/default.jpg', 1852),
('Thunder Pick Keyontae Johnson Throws Down Alley-Oop Jam! 😤| #Shorts', 'XYXkOp32veo', '', 'https://i.ytimg.com/vi/XYXkOp32veo/default.jpg', 1853),
('PISTONS vs MAGIC | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', '7QSVF5KRMZk', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Detroit Pistons defeat the Orlando Magic, 89-78.  Jalen Duren led the way with 17 points and 8 rebounds for the Pistons, while James Wiseman (16 points, 11 rebounds) and Ausar Thompson (7 points, 9 rebounds) added a combined 21 points in the victory.  Kevon Harris tallied 21 points and 6 rebounds for the Magic, while Anthony Black added 17 points, 5 rebounds and 5 assists', 'https://i.ytimg.com/vi/7QSVF5KRMZk/default.jpg', 1854),
('Nike Peach Jam:  New York Renaissance vs. Vegas Elite | FULL GAME', '5syXxfY4Ec0', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/5syXxfY4Ec0/default.jpg', 1855),
('KNICKS vs 76ERS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'xGbCuulkZ38', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/xGbCuulkZ38/default.jpg', 1856),
('Then & Now: The Evolution of Basketball with Scoot Henderson and Carmelo Anthony', '4KrDKhbtpLI', 'Live from NBA Con July 7-9 in Las Vegas. A conversation between two 3rd overall draft picks – Carmelo Anthony & Scoot Henderson\n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/4KrDKhbtpLI/default.jpg', 1857),
('2 Chainz & His Son Pulled Up to NBA Con! 🏀 | #Shorts', 'esp0JbRQ4eE', '', 'https://i.ytimg.com/vi/esp0JbRQ4eE/default.jpg', 1858),
('Then & Now: The Evolution of Basketball | Kareem Abdul-Jabbar & Victor Wembanyama and Isiah Thomas.', 'hMO_3h4Tx2Q', 'Live from NBA Con July 7-9 in Las Vegas. Kareem Abdul-Jabbar, Victor Wembanyama, and Isiah Thomas discuss how the game has transformed over time.\n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/hMO_3h4Tx2Q/default.jpg', 1859),
('Cameron & Cayden Boozer Combine For 31 PTS & 17 AST vs Russell Westbrook\'s Team WHYNOT!', '9L3JYhCQcIo', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/9L3JYhCQcIo/default.jpg', 1860),
('NIGHTRYDAS ELITE vs WHYNOT | NIKE EYBL PEACH JAM | FULL GAME | July 8th, 2023', 'Lx05H5lfLno', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/Lx05H5lfLno/default.jpg', 1861),
('#10 Overall Pick Cason Wallace Is On Fire From 3 In His Summer League Debut! 🙌| #Shorts', 'C1Po3G9vaSc', '', 'https://i.ytimg.com/vi/C1Po3G9vaSc/default.jpg', 1862),
('#6 Overall Pick Anthony Black Gets To The Cup For His 1st Summer League Points! 🔥| #Shorts', 'LCKSeInDfGE', '', 'https://i.ytimg.com/vi/LCKSeInDfGE/default.jpg', 1863),
('TEAM CP3 vs GEORGIA STARS | NIKE EYBL PEACH JAM U15 | FULL GAME | July 8th, 2023', 'vw6oem84VEA', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/vw6oem84VEA/default.jpg', 1864),
('Georgia Stars vs Team Ramey | NIKE EYBL PEACH JAM | FULL GAME | July 8th, 2023', 'nbEepkPDGYo', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/nbEepkPDGYo/default.jpg', 1865),
('Tyrese Haliburton, 2 Chainz, and Halo Live Podcast Taping', '6TfxZjbTsMU', 'Live from NBA Con July 7-9 in Las Vegas. Take a trip with Tyrese Haliburton and father-son duo, Halo & 2Chainz as they discuss their relationship, sports, current events, and life lessons. Tickets at nbacon.com. #nbacon\n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/6TfxZjbTsMU/default.jpg', 1866),
('#10 Overall Pick Cason Wallace Drops 20 PTS (6 Threes) In His Summer League Debut!', 'B0OQamw54BY', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Oklahoma City Thunder defeat the Dallas Mavericks, 91-80.  Cason Wallace led the way with 20 points and 6 3pt. FG for the Thunder, while Chet Holmgren added 16 points, 10 rebounds and 2 blocks in the victory.  Jaden Hardy tallied 24 points and 6 rebounds for the Mavericks.', 'https://i.ytimg.com/vi/B0OQamw54BY/default.jpg', 1867),
('Nike Peach Jam: Why Not vs. Nightrydas | FULL GAME', 'dVItR5pttAw', 'Watch live and remember, after the game concludes go over to the NBA App to watch the rest of today\'s Peach Jam action!\n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/dVItR5pttAw/default.jpg', 1868),
('MAVERICKS vs THUNDER | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', '7Rxo0Dop_sU', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Oklahoma City Thunder defeat the Dallas Mavericks, 91-80.  Cason Wallace led the way with 20 points and 6 3pt. FG for the Thunder, while Chet Holmgren added 16 points, 10 rebounds and 2 blocks in the victory.  Jaden Hardy tallied 24 points and 6 rebounds for the Mavericks.', 'https://i.ytimg.com/vi/7Rxo0Dop_sU/default.jpg', 1869),
('Orlando Robinson GOES OFF For 36 Points In Heat W!', 'wpie4gHodf0', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nLed by Orlando Robinson\'s 36 points and 11 rebounds, the Miami Heat defeat the Boston Celtics, 99-88.  Dru Smith added 16 points, 5 rebounds, 7 assists, 3 steals and 3 3pt. FG in the victory.  Jordan Walsh tallied 18 points and 5 rebounds for the Celtics, while JD Davison added 14 points and 11 assists.', 'https://i.ytimg.com/vi/wpie4gHodf0/default.jpg', 1870),
('Celtics Rookie Jordan Walsh Drops 18 PTS In Summer League Debut!', 'l-JtEVksAUw', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nLed by Orlando Robinson\'s 36 points and 11 rebounds, the Miami Heat defeat the Boston Celtics, 99-88.  Dru Smith added 16 points, 5 rebounds, 7 assists, 3 steals and 3 3pt. FG in the victory.  Jordan Walsh tallied 18 points and 5 rebounds for the Celtics, while JD Davison added 14 points and 11 assists.', 'https://i.ytimg.com/vi/l-JtEVksAUw/default.jpg', 1871),
('HEAT vs CELTICS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'C51exQOADjc', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nLed by Orlando Robinson\'s 36 points and 11 rebounds, the Miami Heat defeat the Boston Celtics, 99-88.  Dru Smith added 16 points, 5 rebounds, 7 assists, 3 steals and 3 3pt. FG in the victory.  Jordan Walsh tallied 18 points and 5 rebounds for the Celtics, while JD Davison added 14 points and 11 assists.', 'https://i.ytimg.com/vi/C51exQOADjc/default.jpg', 1872),
('Play Make Her w/ Karl-Anthony Towns, Malika Andrews, & Jessica Holtz.', '4CQn0AO-iLA', 'Live from NBA Con July 7-9 in Las Vegas. Insights into athlete-agent relationships, diversity in sports, and the future from influential voices Karl-Anthony,Malika Andrews, and Jessica Holtz NBAcon.com\n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/4CQn0AO-iLA/default.jpg', 1873),
('Chet Holmgren with the CHASE-DOWN Block! 😳| #Shorts', 'Zg6VsLtoZsg', '', 'https://i.ytimg.com/vi/Zg6VsLtoZsg/default.jpg', 1874),
('10th Overall Pick Cason Wallace Shines In First Half Of Summer League Action!', 'hndPwffUV-I', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/hndPwffUV-I/default.jpg', 1875),
('WARRIORS vs LAKERS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'BLseKs84l0Y', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Los Angeles Lakers defeated the Golden State Warriors, 103-96. Max Christie led the Lakers with 22 points and 7 rebounds while Cole Swider added 19 points. Gui Santon led the Warriors with 25 points, 7 rebounds, and 2 steals as Brandin Podziemski totaled 9 points and 11 rebounds.', 'https://i.ytimg.com/vi/BLseKs84l0Y/default.jpg', 1876),
('Warriors Gui Santos Drops 25 PTS, 7 REB, 2 STL In Summer League!', 'NKeN1RmGPjY', 'The Los Angeles Lakers defeated the Golden State Warriors, 103-96. Max Christie led the Lakers with 22 points and 7 rebounds while Cole Swider added 19 points. Gui Santon led the Warriors with 25 points, 7 rebounds, and 2 steals as Brandin Podziemski totaled 9 points and 11 rebounds. \n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/NKeN1RmGPjY/default.jpg', 1877),
('KINGS vs HAWKS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'dzrVjz0TMVs', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Sacramento Kings defeated the Atlanta Hawks, 80-76. Jordan Ford led the Kings with 20 points as Kessler Edwards (14 points) and Neemias Queta (13 points, 12 rebounds, 3 assists) totaled 27 points. Brady Manek went 5-10 from beyond the arc on his way to 17 points while AJ Griffin added 12 points and 9 rebounds.', 'https://i.ytimg.com/vi/dzrVjz0TMVs/default.jpg', 1878),
('Max Christie Reaches WAY BACK for the Tomahawk Slam! 😤 | #Shorts', 'QvlCDwUt8uc', '', 'https://i.ytimg.com/vi/QvlCDwUt8uc/default.jpg', 1879),
('SPURS vs HORNETS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'X-W7qMavO-g', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe San Antonio Spurs defeated the Charlotte Hornets, 76-68. Victor Wembanyama totaled 9 points, 8 rebounds, 5 blocks, and 3 assists in his professional debut while Julian Champagnie added 20 points, 8 rebounds, and 6 assists for the Spurs. Brandon Miller led the Hornets with 16 points, 11 rebounds, and 3 steals as James Bouknight scored 14 points and grabbed 9 rebounds.', 'https://i.ytimg.com/vi/X-W7qMavO-g/default.jpg', 1880),
('Julian Champagnie Attacks the Rim for the RIDICULOUS Poster! 💪 | #Shorts', 'uIphLx4zvT0', '', 'https://i.ytimg.com/vi/uIphLx4zvT0/default.jpg', 1881),
('#1 Overall Pick Victor Wembanyama Makes His Summer League Debut!', 'x7l6J0zv_ts', 'The San Antonio Spurs defeated the Charlotte Hornets, 76-68. Victor Wembanyama totaled 9 points, 8 rebounds, 5 blocks, and 3 assists in his professional debut while Julian Champagnie added 20 points, 8 rebounds, and 6 assists for the Spurs. Brandon Miller led the Hornets with 16 points, 11 rebounds, and 3 steals as James Bouknight scored 14 points and grabbed 9 rebounds. \n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/x7l6J0zv_ts/default.jpg', 1882),
('Alley-Oop POSTER By Kai Jones! 🤯 | #Shorts', 'vPEbHWbL_YE', '', 'https://i.ytimg.com/vi/vPEbHWbL_YE/default.jpg', 1883),
('Brandon Miller with the HUGE SLAM off the Steal! 🔥 | #Shorts', 'Te7_2IaSpvk', '', 'https://i.ytimg.com/vi/Te7_2IaSpvk/default.jpg', 1884),
('CAVALIERS vs NETS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'ltwW0KcMn2o', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Cleveland Cavaliers defeated the Brooklyn Nets, 101-97. Sharife Cooper led all scorers with 27 points as Emoni Bates (16 points, 6 rebounds) and Sam Merrill (15 points, 10 rebounds, 5 assists) totaled 31 points for the Cavaliers. Armoni Brooks (17 points, 6 rebounds) and Jalen Wilson (17 points, 5 rebounds) led Brooklyn.', 'https://i.ytimg.com/vi/ltwW0KcMn2o/default.jpg', 1885),
('Brooklyn Nets Rookie Jalen Wilson Drops 17 PTS, 6 REB, 2 BLK In Summer League Debut!', '7gQ0PPp9zrY', 'The Cleveland Cavaliers defeated the Brooklyn Nets, 101-97. Sharife Cooper led all scorers with 27 points as Emoni Bates (16 points, 6 rebounds) and Sam Merrill (15 points, 10 rebounds, 5 assists) totaled 31 points for the Cavaliers. Armoni Brooks (17 points, 6 rebounds) and Jalen Wilson (17 points, 5 rebounds) led Brooklyn. \n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/7gQ0PPp9zrY/default.jpg', 1886),
('Cavaliers Rookie Emoni Bates Puts Up 16 PTS, 6 AST, 2 STL In Summer League Debut!', 'uLGqLwXIxxI', 'The Cleveland Cavaliers defeated the Brooklyn Nets, 101-97. Sharife Cooper led all scorers with 27 points as Emoni Bates (16 points, 6 rebounds) and Sam Merrill (15 points, 10 rebounds, 5 assists) totaled 31 points for the Cavaliers. Armoni Brooks (17 points, 6 rebounds) and Jalen Wilson (17 points, 5 rebounds) led Brooklyn. \n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/uLGqLwXIxxI/default.jpg', 1887),
('#1 Overall Pick Victor Wembanyama’s First Summer League Bucket! 👀 | #Shorts', 'Sjgyl6Fp7SY', '', 'https://i.ytimg.com/vi/Sjgyl6Fp7SY/default.jpg', 1888),
('16th Overall Pick Keyonte George Drops HUGE DOUBLE-DOUBLE | 33 PTS, 10 AST, 6 3PM', 'u7JIo8ABeTs', 'Led by Keyonte George\'s 33 points and 10 assists, the Utah Jazz defeat the LA Clippers, 105-99. Ochai Agbaji added 21 points, 9 rebounds and 5 assists for the Jazz, while Xavier Moon tallied 26 points and 4 rebounds for the Clippers. \n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/u7JIo8ABeTs/default.jpg', 1889),
('CLIPPERS vs JAZZ | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'vEcMufZWia8', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nLed by Keyonte George\'s 33 points and 10 assists, the Utah Jazz defeat the LA Clippers, 105-99. Ochai Agbaji added 21 points, 9 rebounds and 5 assists for the Jazz, while Xavier Moon tallied 26 points and 4 rebounds for the Clippers.', 'https://i.ytimg.com/vi/vEcMufZWia8/default.jpg', 1890),
('BUCKS vs SUNS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'VKX835xm1_E', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Milwaukee Bucks defeat the Phoenix Suns, 84-75. MarJon Beauchamp led the way with 20 points and 6 rebounds for the Bucks, while Tyler Cook added 14 points and 4 rebounds in the victory. Toumani Camara tallied 20 points and 8 rebounds for the Suns.', 'https://i.ytimg.com/vi/VKX835xm1_E/default.jpg', 1891),
('PACERS vs WIZARDS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'pYYbkzLW2MM', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Indiana Pacers defeat the Washington Wizards, 91-83. Bennedict Mathurin led the way with 27 points and 5 rebounds for the Pacers, while Isaiah Jackson added 21 points and 14 rebounds in the victory. Johnny Davis tallied 17 points, 4 rebounds and 3 assists for the Wizards, while Bilal Coulibaly added 9 points and 3 rebounds.', 'https://i.ytimg.com/vi/pYYbkzLW2MM/default.jpg', 1892),
('Tacko Fall Block ➡️ MarJon Beauchamp SELF ALLEY-OOP! 👀 | #Shorts', '02wfJ8Yk2Dw', '', 'https://i.ytimg.com/vi/02wfJ8Yk2Dw/default.jpg', 1893),
('#7 Overall Pick Bilal Coulibaly GOT UP for the Block! 🔥 | #Shorts', 'PYZG7jYQ4v8', '', 'https://i.ytimg.com/vi/PYZG7jYQ4v8/default.jpg', 1894),
('Doris Burke congratulates Kyle Kuzma on his new deal while interviewing Jordan Poole 😂 | #Shorts', 'sH3oxgpYEng', '', 'https://i.ytimg.com/vi/sH3oxgpYEng/default.jpg', 1895),
('BULLS vs GRIZZLIES | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'AHvhFjIT-GE', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Memphis Grizzlies defeated the Chicago Bulls, 87-80. Kenneth Lofton Jr. led the way with 23 points, 4 rebounds and 3 blocks for the Grizzlies, while Jake LaRavia added 15 points, 4 rebounds and 3 assists in the victory. Javon Freeman-Liberty tallied 24 points, 6 rebounds and 5 assists for the Bulls.', 'https://i.ytimg.com/vi/AHvhFjIT-GE/default.jpg', 1896),
('Richard Jefferson explains the inaugural NBA In-Season Tournament! 🍿 | #Shorts', 'S-N5OgDblJI', '', 'https://i.ytimg.com/vi/S-N5OgDblJI/default.jpg', 1897),
('The NBA Cup is Revealed for the First Time EVER! 🏆 | #Shorts', 'odjiCLVWDy0', '', 'https://i.ytimg.com/vi/odjiCLVWDy0/default.jpg', 1898),
('#6 Overall Pick Anthony Black Shines In His Summer League Debut!', '0XibbdITqWg', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Detroit Pistons defeat the Orlando Magic, 89-78.  Jalen Duren led the way with 17 points and 8 rebounds for the Pistons, while James Wiseman (16 points, 11 rebounds) and Ausar Thompson (7 points, 9 rebounds) added a combined 21 points in the victory.  Kevon Harris tallied 21 points and 6 rebounds for the Magic, while Anthony Black added 17 points, 5 rebounds and 5 assists', 'https://i.ytimg.com/vi/0XibbdITqWg/default.jpg', 1899),
('2023 In-Season Tournament East & West Groups Reveal!', '0MuEA5AreTI', 'Starting Nov. 3, all 30 teams will compete for the NBA Cup with 8 teams advancing into the knockout rounds! The tournament semis and championship game will be held in Las Vegas, Dec. 7 and 9! \n\nLearn more about the NBA\'s first-ever In-Season Tournament in the NBA App:  https://app.link.nba.com/-Tournament', 'https://i.ytimg.com/vi/0MuEA5AreTI/default.jpg', 1900),
('Wemby & Kareem Share a moment at NBA Con! 🔥| #Shorts', '85yb-mxD_14', '', 'https://i.ytimg.com/vi/85yb-mxD_14/default.jpg', 1901),
('2023 NBA In-Season Tournament Explained!', 'fT1Vk286308', 'Starting Nov. 3, all 30 teams will compete for the NBA Cup with 8 teams advancing into the knockout rounds! The tournament semis and championship game will be held in Las Vegas, Dec. 7 and 9! \n\nLearn more about the NBA\'s first-ever In-Season Tournament in the NBA App:  https://app.link.nba.com/-Tournament', 'https://i.ytimg.com/vi/fT1Vk286308/default.jpg', 1902),
('Thunder Pick Keyontae Johnson Throws Down Alley-Oop Jam! 😤| #Shorts', 'XYXkOp32veo', '', 'https://i.ytimg.com/vi/XYXkOp32veo/default.jpg', 1903),
('PISTONS vs MAGIC | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', '7QSVF5KRMZk', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Detroit Pistons defeat the Orlando Magic, 89-78.  Jalen Duren led the way with 17 points and 8 rebounds for the Pistons, while James Wiseman (16 points, 11 rebounds) and Ausar Thompson (7 points, 9 rebounds) added a combined 21 points in the victory.  Kevon Harris tallied 21 points and 6 rebounds for the Magic, while Anthony Black added 17 points, 5 rebounds and 5 assists', 'https://i.ytimg.com/vi/7QSVF5KRMZk/default.jpg', 1904),
('Nike Peach Jam:  New York Renaissance vs. Vegas Elite | FULL GAME', '5syXxfY4Ec0', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/5syXxfY4Ec0/default.jpg', 1905),
('KNICKS vs 76ERS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'xGbCuulkZ38', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/xGbCuulkZ38/default.jpg', 1906),
('Then & Now: The Evolution of Basketball with Scoot Henderson and Carmelo Anthony', '4KrDKhbtpLI', 'Live from NBA Con July 7-9 in Las Vegas. A conversation between two 3rd overall draft picks – Carmelo Anthony & Scoot Henderson\n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/4KrDKhbtpLI/default.jpg', 1907),
('2 Chainz & His Son Pulled Up to NBA Con! 🏀 | #Shorts', 'esp0JbRQ4eE', '', 'https://i.ytimg.com/vi/esp0JbRQ4eE/default.jpg', 1908),
('Then & Now: The Evolution of Basketball | Kareem Abdul-Jabbar & Victor Wembanyama and Isiah Thomas.', 'hMO_3h4Tx2Q', 'Live from NBA Con July 7-9 in Las Vegas. Kareem Abdul-Jabbar, Victor Wembanyama, and Isiah Thomas discuss how the game has transformed over time.\n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/hMO_3h4Tx2Q/default.jpg', 1909),
('Cameron & Cayden Boozer Combine For 31 PTS & 17 AST vs Russell Westbrook\'s Team WHYNOT!', '9L3JYhCQcIo', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/9L3JYhCQcIo/default.jpg', 1910),
('NIGHTRYDAS ELITE vs WHYNOT | NIKE EYBL PEACH JAM | FULL GAME | July 8th, 2023', 'Lx05H5lfLno', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/Lx05H5lfLno/default.jpg', 1911),
('#10 Overall Pick Cason Wallace Is On Fire From 3 In His Summer League Debut! 🙌| #Shorts', 'C1Po3G9vaSc', '', 'https://i.ytimg.com/vi/C1Po3G9vaSc/default.jpg', 1912),
('#6 Overall Pick Anthony Black Gets To The Cup For His 1st Summer League Points! 🔥| #Shorts', 'LCKSeInDfGE', '', 'https://i.ytimg.com/vi/LCKSeInDfGE/default.jpg', 1913),
('TEAM CP3 vs GEORGIA STARS | NIKE EYBL PEACH JAM U15 | FULL GAME | July 8th, 2023', 'vw6oem84VEA', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/vw6oem84VEA/default.jpg', 1914),
('Georgia Stars vs Team Ramey | NIKE EYBL PEACH JAM | FULL GAME | July 8th, 2023', 'nbEepkPDGYo', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/nbEepkPDGYo/default.jpg', 1915),
('Tyrese Haliburton, 2 Chainz, and Halo Live Podcast Taping', '6TfxZjbTsMU', 'Live from NBA Con July 7-9 in Las Vegas. Take a trip with Tyrese Haliburton and father-son duo, Halo & 2Chainz as they discuss their relationship, sports, current events, and life lessons. Tickets at nbacon.com. #nbacon\n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/6TfxZjbTsMU/default.jpg', 1916),
('#10 Overall Pick Cason Wallace Drops 20 PTS (6 Threes) In His Summer League Debut!', 'B0OQamw54BY', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Oklahoma City Thunder defeat the Dallas Mavericks, 91-80.  Cason Wallace led the way with 20 points and 6 3pt. FG for the Thunder, while Chet Holmgren added 16 points, 10 rebounds and 2 blocks in the victory.  Jaden Hardy tallied 24 points and 6 rebounds for the Mavericks.', 'https://i.ytimg.com/vi/B0OQamw54BY/default.jpg', 1917),
('Nike Peach Jam: Why Not vs. Nightrydas | FULL GAME', 'dVItR5pttAw', 'Watch live and remember, after the game concludes go over to the NBA App to watch the rest of today\'s Peach Jam action!\n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/dVItR5pttAw/default.jpg', 1918),
('MAVERICKS vs THUNDER | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', '7Rxo0Dop_sU', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Oklahoma City Thunder defeat the Dallas Mavericks, 91-80.  Cason Wallace led the way with 20 points and 6 3pt. FG for the Thunder, while Chet Holmgren added 16 points, 10 rebounds and 2 blocks in the victory.  Jaden Hardy tallied 24 points and 6 rebounds for the Mavericks.', 'https://i.ytimg.com/vi/7Rxo0Dop_sU/default.jpg', 1919),
('Orlando Robinson GOES OFF For 36 Points In Heat W!', 'wpie4gHodf0', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nLed by Orlando Robinson\'s 36 points and 11 rebounds, the Miami Heat defeat the Boston Celtics, 99-88.  Dru Smith added 16 points, 5 rebounds, 7 assists, 3 steals and 3 3pt. FG in the victory.  Jordan Walsh tallied 18 points and 5 rebounds for the Celtics, while JD Davison added 14 points and 11 assists.', 'https://i.ytimg.com/vi/wpie4gHodf0/default.jpg', 1920),
('Celtics Rookie Jordan Walsh Drops 18 PTS In Summer League Debut!', 'l-JtEVksAUw', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nLed by Orlando Robinson\'s 36 points and 11 rebounds, the Miami Heat defeat the Boston Celtics, 99-88.  Dru Smith added 16 points, 5 rebounds, 7 assists, 3 steals and 3 3pt. FG in the victory.  Jordan Walsh tallied 18 points and 5 rebounds for the Celtics, while JD Davison added 14 points and 11 assists.', 'https://i.ytimg.com/vi/l-JtEVksAUw/default.jpg', 1921),
('HEAT vs CELTICS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'C51exQOADjc', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nLed by Orlando Robinson\'s 36 points and 11 rebounds, the Miami Heat defeat the Boston Celtics, 99-88.  Dru Smith added 16 points, 5 rebounds, 7 assists, 3 steals and 3 3pt. FG in the victory.  Jordan Walsh tallied 18 points and 5 rebounds for the Celtics, while JD Davison added 14 points and 11 assists.', 'https://i.ytimg.com/vi/C51exQOADjc/default.jpg', 1922),
('Play Make Her w/ Karl-Anthony Towns, Malika Andrews, & Jessica Holtz.', '4CQn0AO-iLA', 'Live from NBA Con July 7-9 in Las Vegas. Insights into athlete-agent relationships, diversity in sports, and the future from influential voices Karl-Anthony,Malika Andrews, and Jessica Holtz NBAcon.com\n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now ➡ https://app.link.nba.com/APP22\n\nSubscribe to the NBA: https://on.nba.com/2JX5gSN', 'https://i.ytimg.com/vi/4CQn0AO-iLA/default.jpg', 1923),
('Chet Holmgren with the CHASE-DOWN Block! 😳| #Shorts', 'Zg6VsLtoZsg', '', 'https://i.ytimg.com/vi/Zg6VsLtoZsg/default.jpg', 1924),
('10th Overall Pick Cason Wallace Shines In First Half Of Summer League Action!', 'hndPwffUV-I', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/hndPwffUV-I/default.jpg', 1925),
('WARRIORS vs LAKERS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'BLseKs84l0Y', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Los Angeles Lakers defeated the Golden State Warriors, 103-96. Max Christie led the Lakers with 22 points and 7 rebounds while Cole Swider added 19 points. Gui Santon led the Warriors with 25 points, 7 rebounds, and 2 steals as Brandin Podziemski totaled 9 points and 11 rebounds.', 'https://i.ytimg.com/vi/BLseKs84l0Y/default.jpg', 1926),
('Warriors Gui Santos Drops 25 PTS, 7 REB, 2 STL In Summer League!', 'NKeN1RmGPjY', 'The Los Angeles Lakers defeated the Golden State Warriors, 103-96. Max Christie led the Lakers with 22 points and 7 rebounds while Cole Swider added 19 points. Gui Santon led the Warriors with 25 points, 7 rebounds, and 2 steals as Brandin Podziemski totaled 9 points and 11 rebounds. \n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/NKeN1RmGPjY/default.jpg', 1927),
('KINGS vs HAWKS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'dzrVjz0TMVs', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Sacramento Kings defeated the Atlanta Hawks, 80-76. Jordan Ford led the Kings with 20 points as Kessler Edwards (14 points) and Neemias Queta (13 points, 12 rebounds, 3 assists) totaled 27 points. Brady Manek went 5-10 from beyond the arc on his way to 17 points while AJ Griffin added 12 points and 9 rebounds.', 'https://i.ytimg.com/vi/dzrVjz0TMVs/default.jpg', 1928),
('Max Christie Reaches WAY BACK for the Tomahawk Slam! 😤 | #Shorts', 'QvlCDwUt8uc', '', 'https://i.ytimg.com/vi/QvlCDwUt8uc/default.jpg', 1929),
('SPURS vs HORNETS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'X-W7qMavO-g', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe San Antonio Spurs defeated the Charlotte Hornets, 76-68. Victor Wembanyama totaled 9 points, 8 rebounds, 5 blocks, and 3 assists in his professional debut while Julian Champagnie added 20 points, 8 rebounds, and 6 assists for the Spurs. Brandon Miller led the Hornets with 16 points, 11 rebounds, and 3 steals as James Bouknight scored 14 points and grabbed 9 rebounds.', 'https://i.ytimg.com/vi/X-W7qMavO-g/default.jpg', 1930),
('Julian Champagnie Attacks the Rim for the RIDICULOUS Poster! 💪 | #Shorts', 'uIphLx4zvT0', '', 'https://i.ytimg.com/vi/uIphLx4zvT0/default.jpg', 1931),
('#1 Overall Pick Victor Wembanyama Makes His Summer League Debut!', 'x7l6J0zv_ts', 'The San Antonio Spurs defeated the Charlotte Hornets, 76-68. Victor Wembanyama totaled 9 points, 8 rebounds, 5 blocks, and 3 assists in his professional debut while Julian Champagnie added 20 points, 8 rebounds, and 6 assists for the Spurs. Brandon Miller led the Hornets with 16 points, 11 rebounds, and 3 steals as James Bouknight scored 14 points and grabbed 9 rebounds. \n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/x7l6J0zv_ts/default.jpg', 1932),
('Alley-Oop POSTER By Kai Jones! 🤯 | #Shorts', 'vPEbHWbL_YE', '', 'https://i.ytimg.com/vi/vPEbHWbL_YE/default.jpg', 1933),
('Brandon Miller with the HUGE SLAM off the Steal! 🔥 | #Shorts', 'Te7_2IaSpvk', '', 'https://i.ytimg.com/vi/Te7_2IaSpvk/default.jpg', 1934),
('CAVALIERS vs NETS | NBA SUMMER LEAGUE | FULL GAME HIGHLIGHTS', 'ltwW0KcMn2o', 'Never miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22\n\nThe Cleveland Cavaliers defeated the Brooklyn Nets, 101-97. Sharife Cooper led all scorers with 27 points as Emoni Bates (16 points, 6 rebounds) and Sam Merrill (15 points, 10 rebounds, 5 assists) totaled 31 points for the Cavaliers. Armoni Brooks (17 points, 6 rebounds) and Jalen Wilson (17 points, 5 rebounds) led Brooklyn.', 'https://i.ytimg.com/vi/ltwW0KcMn2o/default.jpg', 1935),
('Brooklyn Nets Rookie Jalen Wilson Drops 17 PTS, 6 REB, 2 BLK In Summer League Debut!', '7gQ0PPp9zrY', 'The Cleveland Cavaliers defeated the Brooklyn Nets, 101-97. Sharife Cooper led all scorers with 27 points as Emoni Bates (16 points, 6 rebounds) and Sam Merrill (15 points, 10 rebounds, 5 assists) totaled 31 points for the Cavaliers. Armoni Brooks (17 points, 6 rebounds) and Jalen Wilson (17 points, 5 rebounds) led Brooklyn. \n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/7gQ0PPp9zrY/default.jpg', 1936),
('Cavaliers Rookie Emoni Bates Puts Up 16 PTS, 6 AST, 2 STL In Summer League Debut!', 'uLGqLwXIxxI', 'The Cleveland Cavaliers defeated the Brooklyn Nets, 101-97. Sharife Cooper led all scorers with 27 points as Emoni Bates (16 points, 6 rebounds) and Sam Merrill (15 points, 10 rebounds, 5 assists) totaled 31 points for the Cavaliers. Armoni Brooks (17 points, 6 rebounds) and Jalen Wilson (17 points, 5 rebounds) led Brooklyn. \n\nNever miss a moment with the latest news, trending stories and highlights to bring you closer to your favorite players and teams.\nDownload now: https://app.link.nba.com/APP22', 'https://i.ytimg.com/vi/uLGqLwXIxxI/default.jpg', 1937),
('#1 Overall Pick Victor Wembanyama’s First Summer League Bucket! 👀 | #Shorts', 'Sjgyl6Fp7SY', '', 'https://i.ytimg.com/vi/Sjgyl6Fp7SY/default.jpg', 1938);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `youtube_channels`
--
ALTER TABLE `youtube_channels`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `youtube_channel_videos`
--
ALTER TABLE `youtube_channel_videos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `youtube_channels`
--
ALTER TABLE `youtube_channels`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=58;

--
-- AUTO_INCREMENT for table `youtube_channel_videos`
--
ALTER TABLE `youtube_channel_videos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1939;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
